#!/usr/bin/env python3
"""Generate a process-issued real-capability source for validation-run.

The scanner is deliberately an external, device-aware executable.  This
command never infers or accepts speed/yaw/deadman values from CLI arguments;
the scanner must return the typed ``{"scanner_id", "capability"}`` object.
Run it under the operator's privileged device service so the resulting file is
root-owned and mode 0600, as required by ``validation-run``.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import stat
import subprocess
import sys
ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = ROOT / "src" / "tianji_teleop"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from tianji_teleop.sources.common.real_admission import RealCapabilityInput


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scanner", required=True, help="device-aware scanner executable")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args(argv)
    scanner = Path(args.scanner)
    if not scanner.is_file() or not os.access(scanner, os.X_OK):
        raise SystemExit(f"scanner is not executable: {scanner}")
    if os.geteuid() != 0:
        raise SystemExit("real preflight artifact must be generated by the privileged scanner service (run with sudo)")
    result = subprocess.run([str(scanner)], check=True, capture_output=True, text=True)
    try:
        value = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"scanner returned invalid JSON: {exc}") from exc
    if not isinstance(value, dict) or set(value) != {"scanner_id", "capability"}:
        raise SystemExit("scanner output must contain exactly scanner_id and capability")
    if not isinstance(value["scanner_id"], str) or not value["scanner_id"].strip():
        raise SystemExit("scanner_id must be non-empty")
    try:
        capability = RealCapabilityInput.from_mapping(value["capability"])
    except (TypeError, ValueError) as exc:
        raise SystemExit(f"scanner capability is invalid: {exc}") from exc
    if not capability.admitted:
        raise SystemExit("device-aware scanner denied real admission")
    output = args.output.expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(
        {"scanner_id": value["scanner_id"].strip(), "capability": {
            "speed": capability.speed,
            "yaw_deg": capability.yaw_deg,
            "deadman_available": capability.deadman_available,
            "preflight_passed": capability.preflight_passed,
        }},
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    fd = os.open(output, flags, 0o600)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(payload)
        fd = -1
    finally:
        if fd >= 0:
            os.close(fd)
    mode = stat.S_IMODE(output.stat().st_mode)
    if output.stat().st_uid != 0 or mode != 0o600:
        output.unlink(missing_ok=True)
        raise SystemExit("scanner artifact ownership/mode verification failed")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
